#! /usr/bin/env python

import pnt, off, geojson
import matplotlib
import matplotlib.cm as cm
import matplotlib.mlab as mlab
import matplotlib.pyplot as plt

import pickle, gzip

input_pnt_file   = "tavg-1981-2010--1901-1960.pnt"
pickle_file      = "tavg-1981-2010--1901-1960.pkz"
output_file_base = "tavg-1981-2010--1901-1960"

## print "loading"
## pfile = pnt.PntFile(input_pnt_file)
## print "gridding"
## g = pnt.PntGrid()
## g.load_pntfile(pfile)
## 
## print "pickling"
## with gzip.open(pickle_file, "wb") as f:
##      pickle.dump(g, f)

with gzip.open(pickle_file, "rb") as f:
    g = pickle.load(f)

print "contouring"

plt.figure()
#CS = plt.contour(g.a, 10)
CS = plt.contourf(g.a, 8)

collections = CS.collections
levels = CS.levels               # NOTE: len(collections) = len(levels)

polylists = []
for coll in collections:
    plist = []
    for p in coll.get_paths():
        p.simplify_threshold = 0.0
        plist = plist + p.to_polygons()
    polylists.append(plist)

g = pnt.PntGrid()

off = off.Off()
for i in range(0,len(collections)):
    level    = CS.levels[i]
    for polygon in polylists[i]:
        face = []
        for p in polygon:
            face.append([ g.xTr.int_to_float(p[0]), g.yTr.int_to_float(p[1]), level ])
        off.add_face(face)
off.write(output_file_base + ".off")

fclist = []
for i in range(0,len(collections)):
    fc = geojson.FeatureCollection()
    level    = CS.levels[i]
    fc.features.append(geojson.MultiPolygonFeature("level-%1d" % i, "level-%1d" % i, polylists[i]))
    fclist.append(fc)


for i in range(0,len(fclist)):
    fc = fclist[i]
    outfile = "%s-%02d.json" % (output_file_base,i)
    with open(outfile, "w") as f:
        f.write(fc.toString())
    print "wrote %s" % outfile

#plt.show()
