#! /usr/bin/env python


import re, os


for year in range(1930,2011):
    content = ""
    with open("contourmap.tpl.js", "r") as f:
        for line in f:
             content = content + line
    content = re.sub(r'__YEAR__', "%4d" % year, content)
    with open("contourmap.js", "w") as f:
        f.write(content)

    imgfile = "img-%04d.png" % year

    with open("dopage", "w") as f:
        f.write("var page = require('webpage').create();")
        f.write("page.open('http://localhost/~mbp/mpl/index.html', function () {")
        f.write("    page.render('%s');" % imgfile)
        f.write("    phantom.exit();")
        f.write("});")

    os.system("phantomjs dopage")
    print "wrote %s" % imgfile
