#! /usr/bin/env python

import re, os

for year in range(1916,2013):
    with open("index.html", "r") as f_in:
        with open("index-dopage.html", "w") as f_out:
            for line in f_in:
                if re.search(r'<script\s+type="text/javascript"\s*>\s*window.contourmap', line):
                    f_out.write('<script type="text/javascript">window.contourmap("data/final/22year-anomalies/%04d.contours.json", "%04d");</script>%s' % (
                        year, year, "\n"))
                else:
                    f_out.write(line)

    imgfile = "data/final/22year-anomaly-images/%04d.png" % year

    with open("dopage", "w") as f:
        f.write("var page = require('webpage').create();")
        f.write("page.open('http://localhost/~mbp/mpl/index-dopage.html', function () {")
        f.write("    page.render('%s');" % imgfile)
        f.write("    phantom.exit();")
        f.write("});")

    os.system("phantomjs dopage")
    os.remove("index-dopage.html")
    os.remove("dopage")
    print "wrote %s" % imgfile
