#! /usr/bin/env python

import pnt, sys, optparse, pickle, gzip
import numpy as np

usage = "usage: pkz-subtract OUTFILE.pkz FILE_A.pkz FILE_B.pkz    # computes OUTFILE.pkz = FILE_A.pkz - FILE_B.pkz"

parser = optparse.OptionParser(usage)

(opts, args) = parser.parse_args()

if len(args) < 3:
    print usage
    sys.exit(0)

outfile = args.pop(0)
file_a = pnt.PntGrid.load_pkzfile( args.pop(0) )
file_b = pnt.PntGrid.load_pkzfile( args.pop(0) )
g = pnt.PntGrid.subtract(file_a, file_b)
with gzip.open(outfile, "wb") as f:
    pickle.dump(g, f)
print "wrote %s" % outfile
